language: c

jobs:
  include:
    - os: linux
      compiler: gcc
      script: sh ./ci_build.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)


    - os: linux
      compiler: clang
      script: sh ./ci_build.sh

    - os: linux
      compiler: gcc
      arch: 
        - arm64
        - ppc64le
      script: sh ./ci_build.sh

    - os: linux
      compiler: gcc
      architecture: 
      script: sh ./ci_build.sh

    - os: osx
      compiler: gcc
      script: sh ./ci_build.sh

    - os: osx
      compiler: clang
      script: sh ./ci_build.sh




    - os: windows
      compiler: gcc
      script: gcc tpng.c -Wall -O2 tests\\driver.c -o tests\\tpng_test.exe

    - os: windows
      compiler: clang
      script: clang tpng.c -Wall -O2 tests\\driver.c -o tests\\tpng_test.exe

