language: c

jobs:
  include:
    - os: linux
      compiler: gcc
      script: sh ./ci_build.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)


    - os: linux
      compiler: clang
      script: make



    - os: osx
      compiler: gcc
      script: make

    - os: osx
      compiler: clang
      script: make




    - os: windows
      compiler: gcc
      script: gcc tpng.c -Wall -O2 tests\\driver.c -o tests\\tpng_test.exe

    - os: windows
      compiler: clang
      script: clang tpng.c -Wall -O2 tests\\driver.c -o tests\\tpng_test.exe

