language: c

jobs:
  include:
    - os: linux
      compiler: gcc
      script: make 

    - os: linux
      compiler: clang
      script: make 



    - os: osx
      compiler: gcc
      script: make 

    - os: osx
      compiler: clang
      script: make 




    - os: windows
      compiler: gcc
      script: gcc tpng.c -Wall -O2 tests\\driver.c -o tests\\tpng_test.exe

    - os: windows
      compiler: clang
      script: clang tpng.c -Wall -O2 tests\\driver.c -o tests\\tpng_test.exe

