language: c

jobs:
  include:
    - os: linux
      compiler: gcc
      script: sh ./ci_build.sh --gcov
      after_success:
        - bash <(curl -s https://codecov.io/bash)


    - os: linux
      compiler: clang
      script: sh ./ci_build.sh

      
    - arch: arm64
      os: linux
      compiler: gcc
      script: sh ./ci_build.sh


    - os: linux
      compiler: gcc
      script: sh ./ci_build.sh

    - os: osx
      compiler: gcc
      script: sh ./ci_build.sh

    - os: osx
      compiler: clang
      script: sh ./ci_build.sh




    - os: windows
      compiler: gcc
      script: gcc tpng.c -Wall -O2 tests\\driver.c -o tests\\tpng_test.exe

    - os: windows
      compiler: clang
      script: clang tpng.c -Wall -O2 tests\\driver.c -o tests\\tpng_test.exe

