language: c

jobs:
  include:
    - os: linux
      compiler: gcc
      script: make 

    - os: linux
      compiler: clang
      script: make 


    - os: osx
      compiler: gcc
      script: make 

    - os: windows
      compiler: gcc
      script: make.bat
