language: c

jobs:
  include:
    - os: linux
      compiler: gcc clang
      script: make 

    - os: osx
      compiler: gcc clang
      script: make 


    - os: windows
      compiler: gcc clang
      script: make.bat
